title: Eines Digitals 365
short_title: Eines Digitals 365
email: einesdigitals365@gmail.com
description: >-
  Eines Digitals per a families
url: "https://einesdigitals365.com"
baseurl: "/"
twitter_username: 
github_username: einesdigitals365fixes
instagram_username: einesdigitals365

microsite:
  xarxafixa:
    title: Xarxa Fixa
    url: "https://xarxafixa.com/"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%b %-d, %Y"
  
  social_links:
    - { platform: github,  user_url: "https://github.com/einesdigitals365" }

header_pages:
  - blog.md
  - pages/about.md

show_excerpts: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
