title: Eines Digitals
short_title: Eines Digitals
email: ideesfixes365@gmail.com
description: >-
  Eines digitals per a families
url: "https://idees-fixes.github.io/"
baseurl: "/eines-digitals"
twitter_username: 
github_username: idees-fixes
instagram_username: ideesfixes365

microsite:
  ideesfixes:
    title: Idees Fixes
    url: "https://idees-fixes.github.io/idees-fixes/"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%b %-d, %Y"
  
  social_links:
    - { platform: github,  user_url: "https://github.com/idees-fixes" }

header_pages:
  - blog.md
  - pages/about.md

show_excerpts: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
