title: Blog d'Eines Digitals
email: ideesfixes365@gmail.com
description: >-
  Blog sobre eines digitals per a families.
baseurl: "/blog-eines-digitals"
url: "https://idees-fixes.github.io/"
twitter_username: 
github_username: idees-fixes

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%b %-d, %Y"
  
  social_links:
    - { platform: github,  user_url: "https://github.com/idees-fixes" }

header_pages:
  - about.md

show_excerpts: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
